{% set name = "tortoise-orm" %}
{% set version = "0.17.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tortoise-orm-{{ version }}.tar.gz
  sha256: 8314a9ae63d3f009bac5da3e7d1f7e3f2de8f9bad43ce1efcd3e059209cd3f9d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - aiosqlite >=0.16.0,<0.17.0
    - iso8601 >=0.1.13,<0.2.0
    - pypika-tortoise >=0.1.1,<0.2.0
    - python >=3.6,<4.0
    - pytz

test:
  imports:
    - tortoise
    - tortoise.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tortoise/tortoise-orm
  doc_url: http://tortoise-orm.readthedocs.io/en/latest/
  summary: Easy async ORM for python, built with relations in mind
  license: Apache-2.0
  license_file: LICENSE.txt
  description: |
    Tortoise ORM is an easy-to-use asyncio ORM (Object Relational Mapper)
     inspired by Django. Tortoise ORM was built with relations in mind and
     admiration for the excellent and popular Django ORM. It's engraved in its
     design that you are working not with just tables, you work with relational
     data.

extra:
  recipe-maintainers:
    - thewchan
